### ISSUE TITLE
Deployment 2020-2.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-SIX/profile_collection#30]
## Previsit 
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Check if beamline specific packages pushed to the BL machines
- [x] (Optional) Enable CI

## Housekeeping 
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the profile as-found as 2019C3.x
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)

## Test deployment 
- [x] In `~/.bashrc` add the following and remember to `source ~/.bashrc` afterward.
  ```
  BLUESKY_LOG_FILE=/var/log/bluesky.log
  BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky_ipython.log
  ```
  and (if needed) create those directories, making them world-read/write-able.
- [x] Append to `00-startup.py`  https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2
- [x] Run profile against new environment
  - `BS_ENV=collection-2020-2.0rc7 bsui`
- [x] Update the profile as needed to run:
  - [x] Replace `.value` -> `.get()` if it's in a `Device`, or with `yield from bps.read()` if in a plan
  - [x] `history.sqlite` issue - see https://blueskyproject.io/bluesky/metadata.html#persistence-between-sessions
  - [ ] potential issue with images in databroker V2
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline
- [x] Tag the updated profile as `2020C2.0`
- [x] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by cryos** [comment]
I see some `caput`:
```
plans/03-plan.py:    from epics import caget, caput 
plans/03-plan.py:        caput('XF:02IDA-OP{Mir:1-Ax:4_Pitch}Cmd:Kill-Cmd',1 ) 
plans/03-plan.py:        caput('XF:02IDA-OP{Mir:1-Ax:4_Pitch}Cmd:Kill-Cmd',1 )
```
Also, `.put`:
```
startup/04-epu.py:            self.setpoint.put(self.position)
startup/04-epu.py:        self.setpoint.put(position, wait=False)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.min_xyz.min_x').put(min_x)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.size.x').put(size_x)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.min_xyz.min_y').put(min_y)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.size.y').put(size_y)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.min_xyz.min_z').put(min_z)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.size.z').put(size_z)
startup/22-rixscam.py:        self._acquisition_signal.put(1, wait=False)
startup/November 2018 22-rixscam.pyno:        self._acquisition_signal.put(1, wait=False)
```
PR #31 contains my proposed `.get()` changes.

**Comment by cryos** [comment]
PR #31 is merged, testing now. The `.put` and `caput` mentioned above have not been changed.

**Comment by danielballan** [comment]
Looking at that PV

```
XF:02IDA-OP{Mir:1-Ax:4_Pitch}Cmd:Kill-Cmd
```

they have an ophyd Device connected to that hardware, or so I infer based on the matching PV prefix:

```
startup/10-mirror.py:m1 = M1('XF:02IDA-OP{Mir:1-Ax:4', name='m1')
```

An `M1` is a custom compound device defined in that same file:

```py
from ophyd import Device, EpicsMotor
from ophyd import Component as Cpt

class M1(Device):
    x = Cpt(EpicsMotor, '_Trans}Mtr')
    pit = Cpt(EpicsMotor, '_Pitch}Mtr')
    rol = Cpt(EpicsMotor, '_Roll}Mtr')
```

but `EpicsMotor` has no signal connected to the `Kill-Cmd` PV, as you can verify in https://github.com/bluesky/ophyd/blob/master/ophyd/epics_motor.py.

I do not know off the top of my head if `Kill-Cmd` is common to all EpicsMotors or particular to these. We should investigate that, and then decide whether to add that to `EpicsMotor` or a special subclass here.

**Comment by danielballan** [comment]
```
startup/04-epu.py:            self.setpoint.put(self.position)
startup/04-epu.py:        self.setpoint.put(position, wait=False)

startup/22-rixscam.py:        self._acquisition_signal.put(1, wait=False)
```

These are correct because they are called inside methods on custom ophyd Devices.

```
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.min_xyz.min_x').put(min_x)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.size.x').put(size_x)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.min_xyz.min_y').put(min_y)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.size.y').put(size_y)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.min_xyz.min_z').put(min_z)
startup/21-areadetector.py:            getattr(self, 'roi' + str(roi_num) + '.size.z').put(size_z)
```

...and same here, though a minor refactor could make that code a bit prettier.
